# -----------------------------------------------------------------------------
# CONFIGURACIÓN DE FINANCIACIÓN MYCN18 - DESARROLLADOR ÚNICO (Luke1606)
# -----------------------------------------------------------------------------
# Esta configuración dirige todo el apoyo al desarrollador individual, Luke1606.

# Plataformas de Apoyo Esenciales (Centradas en Código)

# Plataformas de Proyecto y Donación (Activas)

open_collective: MyCn18
thanks_dev: u/gh/luke1606 

# Enlaces Universales Personalizados
# Estos enlaces proporcionan a los usuarios que no están en GitHub formas sencillas de donar
# y opciones de servicio profesional.

custom: [
  'https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=antonioernestoalmaguerzayas@gmail.com',
  'https://Luke1606.dev/mycn18-consulting' # Enlace directo para consultoría profesional u horas de soporte.
]
# -----------------------------------------------------------------------------
